{% set name = "cuda-pathfinder" %}
{% set version = "1.8.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cuda-python/releases/download/{{ name }}-v{{ version }}/cuda-python-{{ name }}-v{{ version }}.tar.gz
  sha256: f6f54318c78821bdc5fd624b5a9029a1abd71d61f169b316e9e31b789caf2ba8

build:
  number: 0
  skip: true  # [py<310 or osx]

requirements:
  host:
    - python
    - pip
    - setuptools >=80.0.0
    - setuptools-scm >=8,!=10.1
    - wheel
  run:
    - python
    - cuda-version >=12.0,<14

test:
  requires:
    - pip
  imports:
    - cuda.pathfinder
  commands:
    - pip check
    - python -c "from cuda.pathfinder import __version__; print(__version__)"
    - python -c "from cuda.pathfinder import SUPPORTED_NVIDIA_LIBNAMES as _cvar; print(_cvar)"
    - python -c "from cuda.pathfinder import LoadedDL; print(dir(LoadedDL))"

about:
  home: https://nvidia.github.io/cuda-python/cuda-pathfinder
  summary: "cuda.pathfinder: Utilities for locating CUDA components in a Python virtual environment"
  description: |
    Public API for loading NVIDIA Dynamic Libraries
  license: Apache-2.0
  license_family: Apache
  license_file: cuda_pathfinder/LICENSE
  doc_url: https://nvidia.github.io/cuda-python/cuda-pathfinder
  dev_url: https://github.com/NVIDIA/cuda-python/tree/main/cuda_pathfinder

extra:
  skip-lints:
    - deprecate_license_url
  recipe-maintainers:
    - conda-forge/cuda-python
    - rwgk
    - leofang
    - kkraus14
    - oleksandr-pavlyk
    - bdice
