{% set name = 'cuda-pathfinder' %}
{% set number = 0 %}
{% set version = '1.3.3' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cuda-python/releases/download/{{ name }}-v{{ version }}/cuda-python-{{ name }}-v{{ version }}.tar.gz
  sha256: 974a06b31bdd594f68f750f713994f31ae0b8b8425434563bdc245187f4815e9

build:
  number: {{ number }}
  skip: true  # [py < 310]
  skip: true  # [osx]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cuda-version >=12.0,<14

test:
  requires:
    - pip
  imports:
    - cuda.pathfinder
  commands:
    - pip check
    - python -c "from cuda.pathfinder import __version__; print(__version__)"
    - python -c "from cuda.pathfinder import SUPPORTED_NVIDIA_LIBNAMES as _cvar; print(_cvar)"
    - python -c "from cuda.pathfinder import LoadedDL; print(dir(LoadedDL))"

about:
  home: https://nvidia.github.io/cuda-python/cuda-pathfinder
  summary: 'cuda.pathfinder: Utilities for locating CUDA components in a Python virtual environment'
  description: |
    Public API for loading NVIDIA Dynamic Libraries
  license: Apache-2.0
  license_file: cuda_pathfinder/LICENSE
  doc_url: https://nvidia.github.io/cuda-python/cuda-pathfinder
  dev_url: https://github.com/NVIDIA/cuda-python/tree/main/cuda_pathfinder

extra:
  recipe-maintainers:
    - conda-forge/cuda-python
    - rwgk
    - leofang
    - kkraus14
    - oleksandr-pavlyk
    - bdice
